workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic2
    environment:
      node: 18
      xcode: 16.2
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.saad.lifestylegym.member1
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm install
      - name: Install Expo CLI
        script: |
          cd mobile-app
          npm install -g expo-cli eas-cli
      - name: Expo prebuild
        script: |
          cd mobile-app
          # حذف المجلد القديم لضمان قراءة رقم الفريق من app.json الجديد
          rm -rf ios
          npx expo prebuild --platform ios --clean --no-install
      - name: Set up code signing
        script: |
          keychain initialize
          xcode-project use-profiles
      - name: Install CocoaPods
        script: |
          cd mobile-app/ios
          pod install
      - name: Build IPA
        script: |
          cd mobile-app
          WORKSPACE=$(find ios -maxdepth 1 -name "*.xcworkspace" -type d | head -1)
          SCHEME=$(basename "$WORKSPACE" .xcworkspace)
          # البناء بدون أي أعلام إضافية لأن المشروع أصبح صحيحاً الآن
          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$SCHEME"
    artifacts:
      - mobile-app/ios/build/remote/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
